export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN_IN_PROGRESS = 'SIGNIN_IN_PROGRESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const GET_ALL_PRODUCTS_IN_PROGRESS = 'GET_ALL_PRODUCTS_IN_PROGRESS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_CART_COUNT = 'GET_CART_COUNT';
